name: Build

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

# Reference
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

jobs:
  build:
    name: Test on python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 1
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Make group jetson_stats
        sudo groupadd jetson_stats
        # Install test dependencies
        sudo ./tests/develop.sh -s
        # Upgrade pip
        sudo -H python -m pip install --upgrade pip
        # Install tox
        sudo -H pip install tox
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Test with tox
      run: |
        sudo tox -e py${{ matrix.python-version }}
